create table if not exists detection_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  node_id text not null,
  cluster_id text not null,
  prediction text not null,
  confidence numeric not null,
  risk_score numeric not null,
  risk_level text not null,
  block_index integer,
  block_hash text not null
);
create index if not exists detection_events_created_at_idx on detection_events(created_at desc);
